### ISSUE TITLE
How to download 7T data?

### ISSUE THREAD

**Issue by yashasvi97** [sreevalsansmenon/IndividualBrainConnectivity#1]
Hi,
Thank you for sharing your code repository, I am trying to reproduce the results and for that I am trying to acquire the 7T hp2000_clean data from HCP. I managed to download the denoised data for 3T (LR/RL sessions), but I was wondering how did you download the 7T (PA/AP sessions )data? Could you please share some example script that might be helpful?

Thanks!

**Comment by sreevalsansmenon** [comment]
We used combination of S3 Browser and https://db.humanconnectome.org at that time. You can use aspera connect to download data from https://db.humanconnectome.org. And I believe the question would be best answered by HCP team as they keep on updating their data curation.
